<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Domain\Bookstore.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.17.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.12" />
    <PackageReference Include="AWSSDK.Rekognition" Version="4.0.101" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.103.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>